language: node_js
node_js:
  - "4.4.7"
install:
  - npm install -g elm
  - (cd example && elm-package install -y)
  - (cd test && elm-package install -y)
script:
  - (cd example && elm make src/BlinkLight.elm)
  - (cd tests && elm make src/Tests.elm --output tests.js && node tests.js)