language: node_js
node_js:
  - "4.4.7"
install:
  - npm install -g elm elm-test
  - (cd example && elm-package install -y)
  - (cd tests && elm-package install -y)
script:
  - (cd example && elm make src/BlinkLight.elm)
  - (elm-test)